# Generated by Django 4.0.2 on 2022-02-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linksapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='category',
            field=models.ManyToManyField(to='linksapp.Category'),
        ),
    ]
